### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by waleedrana777** [hoddy3190/sync-extensions#1]
It would be nice if you said enter file path including file name in description because it causes confusion for user in which format you have to enter file name, I tried entering file name then separated by comma, comes the file path which failed, then added file name after path separated by comma.

What worked was adding file name in the file path. Thanks for extension. Appreciate the work

**Comment by hoddy3190** [comment]
Thank you for your suggestion, and sorry for giving confusion.
I improved README at https://github.com/hoddy3190/sync-extensions/pull/2/commits/f6c0aad8cf862e8371d3084e2004f3bb86059be2 .
